[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
PORT=8000
restartPolicyType = "on_failure"

[[services]]
name = "frontend"
PORT=3000
restartPolicyType = "on_failure"