[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start:api"
healthcheckPath = "/api/backend/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"